### ISSUE TITLE
Issues installing py`tables` on python3.8 on aarm64

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/DMOD#479]
Without some finagling, I was unable to install `tables` on apple arm64 using python3.8. It should be noted that [v3.9.1](https://github.com/PyTables/PyTables/releases/tag/v3.9.1) dropped support for python 3.8. We should discuss how we want to handle this in the near future. I will open another issue to track that.

There are several issues on the `tables` repo that document this issue:

- https://github.com/PyTables/PyTables/issues/1040
- https://github.com/PyTables/PyTables/issues/1055
- https://github.com/PyTables/PyTables/issues/1082

This boils down to an issues with `cython>=3`. 

Like many other project, `tables` uses `pyproject.toml` to specify built time deps. In `3.8.0` (the last version that supports python3.8) they specify the build time dep of cython as [`Cython >=0.29.21`]
(https://github.com/PyTables/PyTables/blob/e34d1f78ed905694672c49a33ef3004a2f8899f2/pyproject.toml#L8C5-L8C21). Because of this, an incompatible version of `cython` is brought in and causes the issue shown in the pip output below.

<details>
<summary>pip output</summary>

```shell
$ env HDF5_DIR=$(brew --prefix hdf5) pip install tables==3.8.0
Collecting tables==3.8.0
  Using cached tables-3.8.0.tar.gz (8.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      ld: library not found for -llzo2
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library not found for -llzo
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      ld: library not found for -lblosc
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      <string>:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

      Error compiling Cython file:
      ------------------------------------------------------------
      ...


      def _dump_h5_backtrace():
          cdef object bt = []

          if H5Ewalk(H5E_DEFAULT, H5E_WALK_DOWNWARD, e_walk_cb, <void*>bt) < 0:
                                                     ^
      ------------------------------------------------------------

      tables/utilsextension.pyx:384:47: Cannot assign type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil' to 'H5E_walk_t'. Exception values are incompatible. Suggest adding 'noexcept' to type 'herr_t (unsigned int, const H5E_error_t *, void *) except? -1 nogil'.
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.8.16 (default, Mar 20 2023, 15:11:41)
      * Found cython 3.0.8
      * USE_PKGCONFIG: True
      * Found HDF5 headers at ``/opt/homebrew/opt/hdf5/include``, library at ``/opt/homebrew/opt/hdf5/lib``.
      * Could not find LZO 2 headers and library; disabling support for it.
      * Could not find LZO 1 headers and library; disabling support for it.
      * Could not find bzip2 headers and library; disabling support for it.
      * Could not find blosc headers and library; using internal sources.
      * Found blosc2 headers at ``/private/var/folders/0h/sb99n9vn58q2n4nsvlh_k6400000gp/T/pip-build-env-_0rr1uc2/overlay/include``, library at ``/private/var/folders/0h/sb99n9vn58q2n4nsvlh_k6400000gp/T/pip-build-env-_0rr1uc2/overlay/lib``.
        * Copying blosc2 runtime library to 'tables' dir because it was not found in standard locations
      Compiling tables/utilsextension.pyx because it changed.
      [1/1] Cythonizing tables/utilsextension.pyx
      Traceback (most recent call last):
        File "/home/test/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/test/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/test/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/0h/sb99n9vn58q2n4nsvlh_k6400000gp/T/pip-build-env-_0rr1uc2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/0h/sb99n9vn58q2n4nsvlh_k6400000gp/T/pip-build-env-_0rr1uc2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/0h/sb99n9vn58q2n4nsvlh_k6400000gp/T/pip-build-env-_0rr1uc2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 928, in <module>
        File "<string>", line 923, in get_cython_extfiles
        File "/private/var/folders/0h/sb99n9vn58q2n4nsvlh_k6400000gp/T/pip-build-env-_0rr1uc2/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/0h/sb99n9vn58q2n4nsvlh_k6400000gp/T/pip-build-env-_0rr1uc2/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: tables/utilsextension.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

```

</details>

Temporary solution:

You can install the [build time deps](https://github.com/PyTables/PyTables/blob/e34d1f78ed905694672c49a33ef3004a2f8899f2/pyproject.toml#L8C5-L8C21) for `3.8.0` manually and then install the package without build isolation. Bearing that you have `HDF5_DIR` set correctly, this should install on 3.8:

```shell
# slightly modified from https://github.com/PyTables/PyTables/blob/e34d1f78ed905694672c49a33ef3004a2f8899f2/pyproject.toml
pip install setuptools >=42.0 wheel oldest-supported-numpy packaging py-cpuinfo Cython ~=0.29.21 blosc2 ~=2.0.0

pip install tables==3.8.0
```

**Comment by christophertubbs** [comment]
Didn't we set the minimum python version to 3.9 due to gitactions testing in 3.9 while we were in 3.8?

**Comment by aaraney** [comment]
We are still testing on 3.8 in our git actions and we say that our min supported python version if 3.8 in [docs/DEPENDENCIES.md](https://github.com/NOAA-OWP/DMOD/blob/2faeb501f80c5ff189d5a7c62b25583b01c6f2a1/doc/DEPENDENCIES.md?plain=1#L23).

**Comment by aaraney** [comment]
My best guess is that it is a non-issue on x86 and the runners are all x86.
