### ISSUE TITLE
class Bag(Collection[_T]): is not subscriptable

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/DMOD#481]
Some of the unit tests have entries like:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/runner/work/DMOD/DMOD/python/lib/client/dmod/test/test_dataset_client.py", line 2, in <module>
    from ..client.request_clients import DataCategory, DatasetClient, DatasetManagementResponse, MaaSDatasetManagementResponse
  File "/home/runner/work/DMOD/DMOD/python/lib/client/dmod/client/request_clients.py", line 2, in <module>
    from dmod.communication import DataServiceClient, ExternalRequestClient, ManagementAction, ModelExecRequestClient, \
  File "/home/runner/work/DMOD/DMOD/dmod_venv/lib/python3.8/site-packages/dmod/communication/__init__.py", line 2, in <module>
    from .client import AuthClient, CachedAuthClient, DataServiceClient, ExternalRequestClient, PartitionerServiceClient, \
  File "/home/runner/work/DMOD/DMOD/dmod_venv/lib/python3.8/site-packages/dmod/communication/client.py", line 14, in <module>
    from .maas_request import ExternalRequest, ExternalRequestResponse
  File "/home/runner/work/DMOD/DMOD/dmod_venv/lib/python3.8/site-packages/dmod/communication/maas_request/__init__.py", line 1, in <module>
    from .utilities import (
  File "/home/runner/work/DMOD/DMOD/dmod_venv/lib/python3.8/site-packages/dmod/communication/maas_request/utilities.py", line 1, in <module>
    from .model_exec_request import ModelExecRequest, get_available_models
  File "/home/runner/work/DMOD/DMOD/dmod_venv/lib/python3.8/site-packages/dmod/communication/maas_request/model_exec_request.py", line 4, in <module>
    from .dmod_job_request import DmodJobRequest
  File "/home/runner/work/DMOD/DMOD/dmod_venv/lib/python3.8/site-packages/dmod/communication/maas_request/dmod_job_request.py", line 7, in <module>
    from dmod.core.meta_data import DataFormat, DataRequirement
  File "/home/runner/work/DMOD/DMOD/dmod_venv/lib/python3.8/site-packages/dmod/core/meta_data.py", line 5, in <module>
    from .common.helper_functions import get_subclasses
  File "/home/runner/work/DMOD/DMOD/dmod_venv/lib/python3.8/site-packages/dmod/core/common/__init__.py", line 22, in <module>
    from .collection import Bag
  File "/home/runner/work/DMOD/DMOD/dmod_venv/lib/python3.8/site-packages/dmod/core/common/collection.py", line 12, in <module>
    class Bag(Collection[_T]):
TypeError: 'ABCMeta' object is not subscriptable
Deactiving active virtual env at /home/runner/work/DMOD/DMOD/dmod_venv
```

The subscript for `Bag(Collection[_T])` just needs to be removed. Bonus points if `typing.Generic[_T]` is added.

**Comment by aaraney** [comment]
I started to work on this earlier this morning and stumbled into #479. Picking it back up now.

**Comment by christophertubbs** [comment]
I was planning on just slapping it together in codespaces after the standup if you don't want to deal with it. Should be a quick turnaround. I don't want you to be too sidetracked if it's not necessary.
