### ISSUE TITLE
Running local GUI server crashes connecting to MAAS_ENDPOINT

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/DMOD#66]
GUI fails to find/create asyncio event loop to establish session.

## Current behavior

Start the gui app server locally:
`MAAS_ENDPOINT_HOST=hostname MAA_ENDPOINT_PORT=port ./manage.py runserver`
from `http://127.0.0.1:8000/` in the browser, configure a request.
The following error occurs in the server log/output

```
EditView.post: making job request
client Making Job Request
PostFormJobRequestClient._acquire_session_info:  getting session info
Session from ModelRequestClient: force_new=False
Connection to request handler web socket
Expecting exception to follow

Failed _acquire_session_info
Traceback (most recent call last):
  File "/Users/nels.frazier/workspace/DMOD/venv/lib/python3.8/site-packages/dmod/communication/client.py", line 349, in _acquire_new_session
    auth_details = asyncio.get_event_loop().run_until_complete(self.authenticate_over_websocket())
  File "/Users/nels.frazier/homebrew/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 639, in g
et_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.
Session Info Return: False
client Unable to aquire session details
```

## Expected behavior

The sessions should establish and push the request to the MAAS_ENDPOINT

**Comment by hellkite500** [comment]
Not sure how this was working before, but my guess is one of the Django updates moved the view handling off the main thread (which is the only one an event loop is created for) and thus there is now no event loop for the view view to use to processes the async DMOD protocol.  Might be able to add this into the view to establish an event loop for the thread itself:
```python
 try:
        loop = asyncio.get_event_loop()
    except RuntimeError:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
 ```
 Also, might want to look at these [Django Async Views](https://docs.djangoproject.com/en/3.1/topics/async/)
and a blog post exploring [async CBV](https://medium.com/@bruno.fosados/django-async-class-based-views-acbv-5986c4511ae6)
