### ISSUE TITLE
No module named 'fastapi'

### ISSUE THREAD

**Issue by christophertubbs** [NOAA-OWP/DMOD#682]
There seems to be a missing entry for `fastapi` in our `requirements.txt`:

```
======================================================================
ERROR: test_dataset_manager_collection (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dataset_manager_collection
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/runner/work/DMOD/DMOD/python/services/dataservice/dmod/test/test_dataset_manager_collection.py", line 13, in <module>
    from .test_required_data_checks_manager import MockDataset, MockDatasetManager
  File "/home/runner/work/DMOD/DMOD/python/services/dataservice/dmod/test/test_required_data_checks_manager.py", line 8, in <module>
    from ..dataservice.service import ActiveOperationTracker, RequiredDataChecksManager
  File "/home/runner/work/DMOD/DMOD/python/services/dataservice/dmod/dataservice/service.py", line 23, in <module>
    from fastapi.websockets import WebSocket
ModuleNotFoundError: No module named 'fastapi'


======================================================================
ERROR: test_required_data_checks_manager (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_required_data_checks_manager
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/runner/work/DMOD/DMOD/python/services/dataservice/dmod/test/test_required_data_checks_manager.py", line 8, in <module>
    from ..dataservice.service import ActiveOperationTracker, RequiredDataChecksManager
  File "/home/runner/work/DMOD/DMOD/python/services/dataservice/dmod/dataservice/service.py", line 23, in <module>
    from fastapi.websockets import WebSocket
ModuleNotFoundError: No module named 'fastapi'
```

Fastapi probably just needs to be added to the requirements.txt file, but this is breaking the unit tests.

**Comment by aaraney** [comment]
For some reason this happens spuriously and it has to do with the environment caching we do in the [update individual packages](https://github.com/NOAA-OWP/DMOD/blob/7dcd6548440228dbe44b1fd1e74795885fb751c7/.github/workflows/testing_and_validation.yml#L56) step. I cleared the runner caches and re-ran the Testing and Validation jobs on `master` and they all passed. Im going to close this for now.
